# Generated by Django 4.2 on 2024-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('plaque', models.CharField(max_length=20)),
                ('vin', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('sub_brand', models.CharField(max_length=20)),
                ('verify_reason', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=15)),
                ('line', models.IntegerField()),
                ('date', models.DateField()),
                ('validity', models.DateField()),
                ('no_tech', models.CharField(max_length=10)),
                ('folio', models.IntegerField()),
                ('validity_init', models.DateField()),
            ],
        ),
    ]
