# Generated by Django 5.0.4 on 2024-05-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='validity_init',
        ),
    ]
