# Generated by Django 5.0.4 on 2024-05-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_remove_vehicle_validity_remove_vehicle_validity_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
