# Generated by Django 5.0.4 on 2024-05-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_alter_vehicle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='no_tech',
            field=models.IntegerField(),
        ),
    ]
