# Generated by Django 5.0.4 on 2024-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_alter_vehicle_no_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='verify_reason',
            field=models.CharField(max_length=30),
        ),
    ]
